### ISSUE TITLE
license

### ISSUE THREAD

**Issue by AK391** [kvfrans/clipdraw#3]
great work, can you please add a license file?

**Comment by z80z80z80** [comment]
I'd also like to have a license for this, open source in the best case :) 
This would enable more people to remix the code and share their changes to this already awesome concept.

**Comment by arnicas** [comment]
Same question - I want to use the results (with credit) in a project, but need a license.  MIT?

**Comment by kvfrans** [comment]
added in a liscence :)

**Comment by Aspie96** [comment]
@kvfrans Thank you a lot for your contribution to open source AI!
